### ISSUE TITLE
typo: mismatch between error suggestion and `config.yml` key

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#267]
When running the following code:
``` r
library(pacta.multi.loanbook)

# As per the instructions in the README.md, I next look at the Cookbook.
# Specifically "Prepartory Steps"

pacta.multi.loanbook::initialise_default_project()
config_path <- "project/config.yml"
pacta.multi.loanbook::prepare_abcd(config_path)
pacta.multi.loanbook::match_loanbooks(config_path)
pacta.multi.loanbook::prioritise_and_diagnose(config_path)
```

I got the error:
``` r
Error in `run_match_prioritize()`:
✖ No manually matched loan book CSVs matching the pattern {.code ^matched_lbk_.*_manual[.]csv$} found.
ℹ Directory searched: /Users/jdhoffa/Downloads/test_multi_loanbook/project/matched_loanbooks
ℹ Check the `dir_output` parameter in your config.yml.
Run `rlang::last_trace()` to see where the error occurred.
```

This error suggested to adjust the `dir_output` parameter, however in the default `config.yml` there is no `dir_output` parameter: 
``` yml
default:
  directories:
    dir_input: "/Users/jdhoffa/Downloads/test_multi_loanbook/project/input"
    dir_prepared_abcd: "/Users/jdhoffa/Downloads/test_multi_loanbook/project/prepared_abcd"
    dir_matched_loanbooks: "/Users/jdhoffa/Downloads/test_multi_loanbook/project/matched_loanbooks"
    dir_prioritized_loanbooks_and_diagnostics: "/Users/jdhoffa/Downloads/test_multi_loanbook/project/prioritized_loanbooks_and_diagnostics"
    dir_analysis: "/Users/jdhoffa/Downloads/test_multi_loanbook/project/analysis"
  file_names:
    filename_scenario_tms: "scenarios_2022_p4b.csv"
    filename_scenario_sda: "scenarios_2022_ei_p4b.csv"
    filename_abcd: "2023-02-17_AI_RMI_PACTA for Banks Free dataset_EO_2022Q4.xlsx"
    sheet_abcd: "Company Indicators - PACTA Comp"
  project_parameters:
    scenario_source: "weo_2022"
    scenario_select: "nze_2050"
    region_select: "global"
    start_year: 2022
    time_frame: 5
    by_group: "group_id"
  sector_split:
    apply_sector_split: TRUE
    filename_split_company_id: "split_company_ids.csv"
    filename_advanced_company_indicators: "2024-02-14_AI_2023Q4_RMI-Company-Indicators.xlsx"
    sheet_advanced_company_indicators: "Company Activities"
  matching:
    params_match_name:
      by_sector: TRUE
      min_score: 0.9
      method: "jw"
      p: 0.1
      overwrite: NULL
      join_id: NULL
    manual_sector_classification:
      use_manual_sector_classification: FALSE
      filename_manual_sector_classification: "manual_sector_classification.csv"
  match_prioritize:
    priority: NULL
  prepare_abcd:
    remove_inactive_companies: TRUE
  match_success_rate:
    plot_width: 12
    plot_height: 8
    plot_units: "in"
    plot_resolution: 300

```
