### ISSUE TITLE
`initialise_default_project()` adds a disruptive newline to the copy of `default_config.yml` that it makes

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#325]
At least on my machine, when I run `initialise_default_project()` the config file that it creates/adds to my project folder contains these lines

``` yaml
  file_names:
    filename_scenario_tms: "2023 IEA JRC ISF Auto Fossil Fuel Power (start year 2023).csv"
    filename_scenario_sda: "2023 CO2 Intensity IEA JRC ISF Steel Cement Aviation (start
      year 2023).csv"
    filename_abcd: "2023-02-17_AI_RMI_PACTA for Banks Free dataset_EO_2022Q4.xlsx"
    sheet_abcd: "Company Indicators - PACTA Comp"
```

while if I run `file.edit(system.file("default_config.yml", package = "pacta.multi.loanbook"))` to open the "default_config.yml" included with my local pacta.multi.loanbook installation, I have

``` yaml
  file_names:
    filename_scenario_tms: "2023 IEA JRC ISF Auto Fossil Fuel Power (start year 2023).csv"
    filename_scenario_sda: "2023 CO2 Intensity IEA JRC ISF Steel Cement Aviation (start year 2023).csv"
    filename_abcd: "2023-02-17_AI_RMI_PACTA for Banks Free dataset_EO_2022Q4.xlsx"
    sheet_abcd: "Company Indicators - PACTA Comp"
```

So far, I haven't been able to figure out why that extra newline appears in the middle of the filename for `filename_scenario_sda`.
